service_code_ec2: "AmazonEC2"
service_code_eks: "AmazonEKS"
ec2_filter_path: "./price/resources/filters/ec2_filters.json"
ebs_filter_path: "./price/resources/filters/ebs_filters.json"
eks_filter_path: "./price/resources/filters/eks_filters.json"
ec2_sku: "PZHVQ3KFPA3RHA5V"
ebs_sku: "HYU9KEWRBJTDDSCK"
eks_sku: "8HAE52ZNS3QC3Q8Q"
region: "ap-northeast-2"
profile: "default"
